apiVersion: v1
kind: Namespace
metadata:
  name: web
  labels:
    name: web
    purpose: application
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
    purpose: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: rollouts
  labels:
    name: rollouts
    purpose: progressive-delivery
---
apiVersion: v1
kind: Namespace
metadata:
  name: canary-demo
  labels:
    name: canary-demo
    purpose: canary-demo

