apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: require-signed-w10-api
spec:
  mode: enforce
  images:
    - glob: "ghcr.io/nvtank/w10-api*"
  authorities:
    - name: authority-0
      key:
        data: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEG/UerSPwaCvNq/tAeoWEXPrSEDpO
          Pd5GVcJBPTCICIsWNhT/OhZd6aF4yqVvJ0RWo59gEx3hpiUcnE98JWTQmA==
          -----END PUBLIC KEY-----
