apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: require-signed-w10-api
spec:
  mode: enforce
  images:
    - glob: "ghcr.io/nvtank/w10-api:*"
  authorities:
    - name: authority-0
      key:
        data: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE80CL5NkFhFq9pr2Q4NhA/7ih6PEM
          xlmuNP7t5K2ivFFbTmVfm8lMmtaihcbDVRVRdgPXTPKM6hN9zH/HcxCHIA==
          -----END PUBLIC KEY-----
