# Lab 5: app-of-apps root
# Root App: App of Apps pattern - quản lý tất cả child applications
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nvtank/xbrain-phase2/
    path: w10/temp/argocd/apps
    targetRevision: w10
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
